### ISSUE TITLE
[BUG] gitignore file is ignored - .env files are pushed to the github repo

### ISSUE THREAD

**Issue by engelmatt** [mamertofabian/bolt-to-github#1]
## 🐛 Bug Description
It seems the app does ignore the .gitignore file. Although .env files are included, the plugin pushes those sensitive files to github which could be desastreous. The bolt.new download feature doesn't make this mistake; the zip file doesn't contain the excluded parts.

Btw I love the plugin. Thanks a lot!
P.S: If one commits only small changes, there is no indication that something happened at all because it finished that fast. Would be great to get some kind of indication the upload was succesful.

**Comment by mamertofabian** [comment]
Thank you @engelmatt for creating this issue! Your input is incredibly helpful for this project. 

Upon reviewing the native `bolt.new` download, I found that it includes everything and does not inspect the `.gitignore`. 

However, your concern about this is valid when pushing to GitHub, so I have made some adjustments to check for the existence of the `.gitignore` file and exclude files accordingly.

Regarding the issue with the indicator not showing up, I have implemented some changes that should fix it. From my quick tests, it seems to be resolved, but please let me know if you still encounter the problem.

Additionally, the extension now supports multiple projects and repositories. Please note that this requires re-entering your GitHub settings.
