### ISSUE TITLE
[BUG] Please configure your GitHub settings first - Configured everything correctly

### ISSUE THREAD

**Issue by growthpods** [mamertofabian/bolt-to-github#5]
## 📝 Steps to Reproduce
3. See error '...'

## 🔍 Environment Details
- Chrome Version: 
- Extension Version: 
- Operating System: 
- Bolt.new Project Type: 

## 💾 Additional Context

- Did this work before?
- Are you using any specific GitHub organization/repository settings?
- Any error messages in the Chrome DevTools console? (Press F12 to open)

## ✔️ Checklist

- [x] I am on bolt.new website when trying to use the extension
- [x] I have provided my GitHub token with correct permissions
- [x] I have the latest version of the extension installed
- [x] I have checked the extension popup for any error messages

**Comment by lucasmpramos** [comment]
I did those and still doesn't work

**Comment by aidrivencoder** [comment]
🚀 Version 1.1.0 is now live on Chrome Web Store and should fix this issue. Plus, there's a new Projects tab that lets you view all your pushed projects in one place and reload them back into Bolt.
Please update and let me know if you're still experiencing any problems!
