### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Webylon** [mamertofabian/bolt-to-github#9]
The plugin was installed and the settings were saved successfully.
Also importing Github repos is working properly.

## ✅ Expected Behavior
When trying to click the Github icon to upload and push the new version it should work as expected

## ❌ Actual Behavior
Unfortunately the loading indicator freezes and nothing happens (see attached image)

## 📸 Screenshots
<img width="530" alt="Skärmavbild 2024-12-22 kl  19 07 00" src="https://github.com/user-attachments/assets/5c3feabb-522c-44ea-a73a-56a3007fc0cb" />

## 🔍 Environment Details
- Chrome Version: 131.0.6778.205 (Officiell version)
- Extension Version: 1.1.0
- Operating System: MacOs Sonoma 14.5
- Bolt.new Project Type: React Web app

## 💾 Additional Context

- Did this work before?
- Are you using any specific GitHub organization/repository settings?
- Any error messages in the Chrome DevTools console? (Press F12 to open)

## ✔️ Checklist

- [ x ] I am on bolt.new website when trying to use the extension
- [ x ] I have provided my GitHub token with correct permissions
- [ x ] I have the latest version of the extension installed
- [ x ] I have checked the extension popup for any error messages

**Comment by mamertofabian** [comment]
Thanks, @Webylon, for creating an issue. This issue has been resolved in version 1.1.1, which is under review in the Chrome Web Store, submitted on Dec 20, 2024. But this repo already has the latest version. You can try to install the extension manually by loading the latest release zip file. Thanks!

_Note: I'm keeping this issue open until version 1.1.1 is Published in CWS._

**Comment by Webylon** [comment]
> Thanks, @Webylon, for creating an issue. This issue has been resolved in version 1.1.1, which is under review in the Chrome Web Store, submitted on Dec 20, 2024. But this repo already has the latest version. You can try to install the extension manually by loading the latest release zip file. Thanks!
> 
> _Note: I'm keeping this issue open until version 1.1.1 is Published in CWS._

@mamertofabian Got it, looking forward to trying out the latest version thank you!

**Comment by Webylon** [comment]
@mamertofabian Will the extension work if I set my project to Private?

**Comment by mamertofabian** [comment]
@Webylon The latest version has been approved. I'm closing this issue now. Thanks for your patience.

**Comment by mamertofabian** [comment]
> @mamertofabian Will the extension work if I set my project to Private?

@Webylon Yes, pushing to Github will work. Though you won't be able to load from GitHub to Bolt.

**Comment by Webylon** [comment]
@mamertofabian Ok, just updated to the latest version and will try it out thank you!
